services:
  - type: web
    name: blazer-sos
    env: php
    plan: standard
    healthCheckPath: /health
    buildCommand: ./build.sh
    startCommand: heroku-php-nginx -C nginx.conf public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: blazer-sos
          type: web
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: blazer-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: blazer-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: blazer-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: blazer-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: blazer-db
          property: password
      - key: MAIL_MAILER
        value: smtp

  # Optionally add a database service
databases:
  - name: blazer-db
    plan: standard
