services:
  - type: web
    name: blazer-sos
    runtime: docker
    buildCommand: ./build.sh
    healthCheckPath: /health
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: blazer-sos
          type: web
          property: host
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite  # Changed to use /tmp instead of /var/data
      - key: MAIL_MAILER
        value: smtp
    # Removed disk configuration