services:
  - type: web
    name: blazer-sos
    runtime: heroku-php
    buildCommand: ./build.sh
    startCommand: vendor/bin/heroku-php-nginx -C nginx.conf public/
    healthCheckPath: /health
    plan: standard
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: blazer-sos
          type: web
          property: host
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: MAIL_MAILER
        value: smtp
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
